project: 
  type: website
  
website: 
  reader-mode: true
  page-navigation: true
  title: "pydatavolley"
  page-footer:
    left: |
      Written by Tyler Widdison, Maurizio Napolitano.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  site-url: pydatavolley.openvolley.org
  repo-branch: gh-pages
  navbar: 
    right: 
      - icon: github
        href: https://github.com
        aria-label: GitHub
  
  sidebar:
    style: docked
    search: true
    collapse-level: 1
    contents:
      - index.qmd
      - section: 1 - Setup
        contents:
          - ide.qmd
          - install_packages.qmd
      - section: 2 - DVW files
        contents:
          - reading_files.qmd
          - data_clean.qmd
      - section: 3 - Creating data
        contents:
          - data_description.qmd
          - heatmaps.qmd

format: 
  html:
    theme:
      - cosmo
      - pydv.scss
    toc: true
    code-fold: show
    code-link: true
    callout-appearance: simple
    author-meta: "Tyler Widdison"

editor: visual