project: 
  type: website
  
website: 
  page-navigation: true
  title: "Exploring with datavolley: Python and R at Openvolley"
  page-footer:
    left: |
      Written by Tyler Widdison
  site-url: pydatavolley.openvolley.org
  repo-branch: gh-pages
  navbar: 
    logo: https://avatars.slack-edge.com/2021-01-31/1719076279312_f2c733e323dab6cfc11b_88.png
    right: 
      - icon: github
        href: https://github.com/openvolley
        aria-label: GitHub

  sidebar:
    style: docked
    collapse-level: 1
    contents:
      - section: "Basics"
        contents:
          - index.qmd
          - tools.qmd
          - install_packages.qmd
      - section: DVW files
        contents:
          - reading_files.qmd
          - filtering.qmd
      - section: Heatmaps
        contents:
          - heatmaps.qmd

format: 
  html:
    theme:
      - cosmo
      - pydv.scss
    toc: true
    code-fold: show
    code-link: true
    callout-appearance: simple
    author-meta: "Tyler Widdison"

editor: visual