project: 
  type: website
  
website: 
  site-url: https://pydatavolley.openvolley.org
  page-navigation: true
  title: "openvolley - Data analysis in R and Python"
  page-footer:
    left: |
      Written by Tyler Widdison
  navbar: 
    logo: https://avatars.slack-edge.com/2021-01-31/1719076279312_f2c733e323dab6cfc11b_88.png
    right: 
      - icon: github
        href: https://github.com/openvolley
        aria-label: GitHub

  sidebar:
    style: "docked"
    search: true
    pinned: true
    collapse-level: 1
    contents:
      - section: index.qmd
      - section: "Basics"
        contents:
          - tools.qmd
          - install_packages.qmd
          - reading_files.qmd
      - section: Data wrangling
        contents:
          - selecting.qmd
          - filtering.qmd
          - additions.qmd
      - section: Heatmaps
        contents:
          - heatmaps.qmd

format: 
  html:
    theme:
      - cosmo
      - pydv.scss
    toc: true
    code-fold: show
    code-link: true
    author-meta: "Tyler Widdison"
