---
project:
  type: website
  output-dir: pydatavolley
  production_url: "https://github.com/openvolley/pydatavolley"
  github_repo_url: openvolley/pydatavolley
navbar:
  - name: "About"
    target:
    - name: "About pydatavolley"
      taret: about/
---
